name: build on openSUSE Tumbleweed

on:
  workflow_dispatch:
    inputs:
      target:
        description: "选择构建类型"
        required: true
        default: "htop"
        type: choice
        options:
          - htop
          - sway
          - foot
          - git

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: registry.opensuse.org/opensuse/tumbleweed

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        if: ${{ inputs.target == 'htop' }}
        run: |
          zypper -n refresh
          zypper -n install --no-recommends \
            gcc gcc-c++ make cmake ninja git pkg-config \
            libopenssl-devel zlib-devel ncurses-devel autoconf libtool

      - name: Configure&build
        if: ${{ inputs.target == 'htop' }}
        env:
          CFLAGS: -O3 -g -flto
          LDFLAGS: -O3 -g -flto
        run: |
            ./configure
            make -k

      - name: Upload artifacts
        if: ${{ inputs.target == 'htop' }}
        uses: actions/upload-artifact@v4
        with:
         name: htop
         path: ./htop/htop
