name: build on openSUSE Tumbleweed

on:
  workflow_dispatch:
    inputs:
      target:
        description: "选择构建类型"
        required: true
        default: "htop"
        type: choice
        options:
          - htop
          - sway
          - foot
          - git
          - wl-clipboard

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: registry.opensuse.org/opensuse/tumbleweed

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        if: ${{ inputs.target == 'htop' }}
        run: |
          zypper -n refresh
          zypper -n install --no-recommends \
            gcc gcc-c++ make cmake ninja git pkg-config \
            libopenssl-devel zlib-devel ncurses-devel autoconf libtool

      - name: Configure&build
        if: ${{ inputs.target == 'htop' }}
        env:
          CFLAGS: -O3 -g -flto
          LDFLAGS: -O3 -g -flto
        run: |
           git clone https://github.com/htop-dev/htop
            cd htop
            ./autogen.sh
            ./autogen.sh
            ./configure
            make -k

      - name: Upload artifacts
        if: ${{ inputs.target == 'htop' }}
        uses: actions/upload-artifact@v4
        with:
         name: htop
         path: ./htop/htop


      - name: Install build dependencies
        if: ${{ inputs.target == 'foot' }}
        run: |
          zypper -n refresh
          zypper -n install --no-recommends \
            gcc gcc-c++ make cmake ninja git pkg-config \
            meson wayland-protocols-devel ncurses-devel libxkbcommon-devel libpixman-1-0-devel fontconfig-devel freetype2-devel tar wayland-devel
            
      - name: Configure&build
        if: ${{ inputs.target == 'foot' }}
        env:
          CFLAGS: -O3 -g -flto
          LDFLAGS: -O3 -g -flto
        run: |
           curl -L https://codeberg.org/dnkl/foot/releases/download/1.26.1/foot-1.26.1.tar.gz -o foot-1.26.1.tar.gz
           tar xvf foot-1.26.1.tar.gz
            cd foot-1.26.1
            mkdir -p bld/release && cd bld/release
            meson --buildtype=release --prefix=/usr -Db_lto=true ../..
            ninja

      - name: Upload artifacts
        if: ${{ inputs.target == 'foot' }}
        uses: actions/upload-artifact@v4
        with:
         name: foot
         path: ./foot-1.26.1

      - name: Install build dependencies
        if: ${{ inputs.target == 'sway' }}
        run: |
          zypper -n refresh
          zypper -n install --no-recommends \
            gcc gcc-c++ make cmake git ninja pkg-config \
            meson wayland-protocols-devel wlroots-devel pcre2-devel libjson-c-devel pango-devel wayland-devel cairo-devel libevdev-devel
            
      - name: Configure&build
        if: ${{ inputs.target == 'sway' }}
        env:
          CFLAGS: -O3 -g -flto
          LDFLAGS: -O3 -g -flto
        run: |
           git clone https://github.com/swaywm/sway
           cd sway
           git checkout 1.12-rc2
           meson setup build/
           ninja -C build/
           git clone https://github.com/swaywm/swaybg/
           cd swaybg
           git checkout v1.2.2
           meson build/
           ninja -C build/

      - name: Upload artifacts
        if: ${{ inputs.target == 'sway' }}
        uses: actions/upload-artifact@v4
        with:
         name: sway
         path: ./sway

      - name: Install build dependencies
        if: ${{ inputs.target == 'wl-clipboard' }}
        run: |
          zypper -n refresh
          zypper -n install --no-recommends \
            gcc gcc-c++ make cmake git ninja pkg-config \
            meson wayland-protocols-devel wlroots-devel pcre2-devel libjson-c-devel pango-devel wayland-devel cairo-devel
            
      - name: Configure&build
        if: ${{ inputs.target == 'wl-clipboard' }}
        run: |
           git clone https://github.com/bugaevc/wl-clipboard.git
           cd wl-clipboard
           meson setup build/
           ninja -C build/

      - name: Upload artifacts
        if: ${{ inputs.target == 'wl-clipboard' }}
        uses: actions/upload-artifact@v4
        with:
         name: wl-clipboard
         path: ./wl-clipboard
