name: build on openSUSE Tumbleweed

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      target:
        description: "选择构建类型"
        required: true
        default: "htop"
        type: choice
        options:
          - htop
          - sway
          - foot
          - git

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: registry.opensuse.org/opensuse/tumbleweed

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          zypper -n refresh
          zypper -n install --no-recommends \
            gcc gcc-c++ make cmake ninja git pkg-config \
            libopenssl-devel zlib-devel
          if [ "${{ inputs.target }}" = "htop" ]; then
            zypper -n install --no-recommends ncurses-devel
          elif [ "${{ inputs.target }}" = "sway" ]; then
            zypper -n install --no-recommends wayland-devel

          elif [ "${{ inputs.target }}" = "foot" ]; then
            zypper -n install --no-recommends wayland-devel

          else
            zypper -n install --no-recommends git
          fi

      - name: Configure&build
        run: |
          if [ "${{ inputs.target }}" = "htop" ]; then
            git clone https://github.com/htop-dev/htop
            cd htop
            ./autogen.sh
            ./configure --enable-static 
            make -j
          elif [ "${{ inputs.target }}" = "sway" ]; then
            echo "ok"

          elif [ "${{ inputs.target }}" = "foot" ]; then
            echo "ok"

          else
           echo "ok"
          fi

      - name: Upload artifacts
        if: ${{ inputs.target == 'htop' }}
        uses: actions/upload-artifact@v4
        with:
         name: htop
         path: ./htop/htop
